### ISSUE TITLE
反光板检测部分关于第一块反光板的处理

### ISSUE THREAD

**Issue by Cracks-ll** [ShihanWang/reflector_ekf_slam#11]
您好，在学习您的代码过程中，对于第一块反光板的处理不是清楚，希望得到您的解答。
https://github.com/ShihanWang/reflector_ekf_slam/blob/22239ab7c095f75341381200197a0dcf52a8c33a/src/reflector_detect/laser/laser_reflector_detect.cc#L205
https://github.com/ShihanWang/reflector_ekf_slam/blob/22239ab7c095f75341381200197a0dcf52a8c33a/src/reflector_detect/laser/laser_reflector_detect.cc#L226
主要上述两段代码，它的原理是什么呢？

**Comment by ShihanWang** [comment]
考虑360度激光雷达，应该判断首尾的反光板是否同一块反光板

**Comment by Cracks-ll** [comment]
> 考虑360度激光雷达，应该判断首尾的反光板是否同一块反光板

对于这部分代码，其整体作用我是明白的，但是在求取first_reflector_length 时，1和2中有关边界点的选择是基于什么考虑呢?
 @ShihanWang 万分期待得到您的解答，十分感谢！！！

> 1.  if (is_circle_scan && last_reflector_last_point_id == 0)
            {
                // Process first reflector
                const float first_reflector_length = (first_reflector_last_point - last_reflector_first_point).norm();
                // Delete first reflector
                if (fabs(first_reflector_length - options_.reflector_min_length) >= options_.reflector_length_error)
                {
                    reflector_points.pop_front();
                }
            }

> 2. else if (is_circle_scan && reflector_ids.front().front() == 0)
    {
        // Only process first reflector
        const float first_reflector_length =
            (reflector_points.front().front().head<2>() - reflector_points.back().front().head<2>()).norm();
        // Delete first reflector
        if (fabs(first_reflector_length - options_.reflector_min_length) >= options_.reflector_length_error)
        {
            reflector_points.pop_front();
        }
    }

**Comment by Cracks-ll** [comment]
我想了想如按照代码中的边界点选择方式
代码1 应该是fabs(first_reflector_length - options_.reflector_min_length) <= options_.reflector_length_error
代码2 应该是fabs(first_reflector_length - options_.reflector_min_length) >= options_.reflector_length_error
@ShihanWang

**Comment by Cracks-ll** [comment]
last_reflector_last_point_id 有等于0的情况存在吗？ @ShihanWang

**Comment by ShihanWang** [comment]
有这种可能，假如垂直于激光雷达0度角的方向上正好有一个反光板，此时激光雷达的第一个点会被认定为反光板

**Comment by Cracks-ll** [comment]
> 有这种可能，假如垂直于激光雷达0度角的方向上正好有一个反光板，此时激光雷达的第一个点会被认定为反光板
这个指的是扫描起始角度是0度，然后0都方向上正好有一条垂直指向天的反光线（智能获得一个强反光点），然后此时的last_reflector_last_point_id就是0，是吗？

**Comment by ShihanWang** [comment]
是的
