### ISSUE TITLE
关于坐标系和反光板匹配的问题

### ISSUE THREAD

**Issue by charon-cheung** [ShihanWang/reflector_ekf_slam#3]
getObservations函数里，lambda表达式point_transformed是把激光点在laser坐标系的坐标转换到base_link坐标系下了，也就是说obs.cloud_在base_link坐标系，但注释是说先转到odom坐标系再转到global坐标系。 地图文件中的坐标应当是事先保存的map坐标， 不应和obs.cloud_比较马氏距离吧

**Comment by ShihanWang** [comment]
观测到的反光板在getObservations函数里转换到base_link坐标系下了，在匹配函数中：detectMatchedIds：585行将反光板转换到全局坐标系下了。所以和地图文件中比较的是不是base_linke下的反光板，而是全局坐标系下的

**Comment by ShihanWang** [comment]
代码已修复
