### ISSUE TITLE
只上传了bag，没上传地图文件test.txt

### ISSUE THREAD

**Issue by charon-cheung** [ShihanWang/reflector_ekf_slam#5]

**Comment by ShihanWang** [comment]
现在只开放了建图数据集，定位数据集尚未开放，所以没有test.txt文档

**Comment by charon-cheung** [comment]
那程序还是运行不了啊，map_path那里报错，不明白这个程序的用意

**Comment by charon-cheung** [comment]
不明白你的意思，我自己建了test.txt，修改了slam_node.cc部分代码，运行后也没有向test_new.txt写入内容，不知道怎么用

**Comment by ShihanWang** [comment]
改一下ReflectorEKFSLAM::~ReflectorEKFSLAM()函数，在这个析构函数里写的保存，把 if(!map_path_.empty() && !map_.reflector_map_.empty())改为 if(!map_path_.empty())

**Comment by chenxinyuzdshuai** [comment]
改了代码重新编译运行后还是会报错：no such file
请问是什么问题

**Comment by chenxinyuzdshuai** [comment]
没有test.txt文件这个代码好像跑不了 ，能再开源一下test.txt文件吗
