### ISSUE TITLE
10cm宽反光条和直径10cm反光桶可以混用不？

### ISSUE THREAD

**Issue by xbcdbc** [ShihanWang/reflector_ekf_slam#7]

**Comment by ShihanWang** [comment]
可以用，不过需要你改一下反光板检测的程序，目前只支持平面的反光板，不支持圆柱形的反光板

**Comment by xbcdbc** [comment]
那请问，同一场景既有反光桶和反光板，怎么区分检测到是反光桶和反光板。期待您的回复，感谢。

**Comment by ShihanWang** [comment]
如果混用，平面的反光板长度和圆柱型的反光板的直径最好不一样，就可以通过长度区分开。否则，需要考虑曲率信息来进行区分
